In [2]:
import pandas as pd
import datetime
import vk_api
import os
import requests
import json
import random

In [3]:
token = 'vk1.a.ggJWr2-ewNyz3IJc64qiyoUsgdJeDgjx6P3PLnv80iDzjF_jKM72X7UKFflTMojJmfjPtAByED37FNlsYamD0LcMpd6VeUauW86CVySTr0YWwAEh74PzjyBtteXtXPcD-BOi_KM0-cIxMaF0GRxTVVuBamunAf7d5iJlI5EGtlosByS15GyOOw0_RrD5b4V7SYg4Qoq_Qd_ggRAJQ1evoA'

In [9]:
vk_sesion = vk_api.VkApi(token=token)
vk = vk_sesion.get_api()

In [11]:
vk.messages.send(
    chat_id=1,
    random_id=2,
    message='Хуй соси'
)

0

In [13]:
#vk.groups.get(user_id=201773026)

In [15]:
df = pd.read_csv('D:\\Программы\\Karpov.Courses - Аналитик данных (2022)\\Часть 1\\Задания\\Ноутбуки и датасеты\\Ноутбуки и датасеты\\lesson_5_ads_data.csv.zip',compression='zip')

In [52]:
df.head()

,ad_id,time,event,date,ad_cost_type,has_video,client_union_id,campaign_union_id,platform,ad_cost,target_audience_count,user_id
0,23456,1554076848,view,2019-04-01,CPM,0,5681,23456,android,190.0,125560,793
1,111941,1554135866,view,2019-04-01,CPM,0,111793,111941,ios,215.2,32277,1041
2,111941,1554135866,view,2019-04-01,CPM,0,111793,111941,ios,215.2,32277,41
3,42987,1554135866,view,2019-04-01,CPM,0,28541,42985,ios,199.1,80160,898
4,23456,1554135866,view,2019-04-01,CPM,0,5681,23456,web,190.0,125560,29

In [57]:
ad_data = ad_data.pivot(index='ad_id', columns='event', values='user_id').reset_index()

In [60]:
ad_data = ad_data.fillna(0).assign(ctr=ad_data.click / ad_data.view)

In [61]:
ad_data

event   ad_id  click    view       ctr
0           3    9.0   490.0  0.018367
1        2132    1.0    95.0  0.010526
2        2276    2.0  1454.0  0.001376
3        2475    0.0   132.0       NaN
4        2643    3.0   286.0  0.010490
..        ...    ...     ...       ...
350    121941    1.0   640.0  0.001563
351    121943   15.0  1722.0  0.008711
352    122042    1.0   155.0  0.006452
353    122063    1.0   260.0  0.003846
354    122086   50.0  1999.0  0.025013

[355 rows x 4 columns]

In [71]:
top_ctr = ad_data.query('click > 20 and view > 100').sort_values('ctr')

In [72]:
top_ctr.to_csv('top_ctr_data.csv', index=False)

In [73]:
import os
print(os.getcwd())

C:\Users\user\PyCharmMiscProject

In [80]:
path = 'C:\\Users\\user\\PyCharmMiscProject\\top_ctr_data.csv'
file_name = 'top_ctr_data.csv'

path_to_file = path
upload_url = vk.docs.getMessagesUploadServer(peer_id=2000000001)['upload_url']
file = {'file': (file_name, open(path_to_file, 'rb'))}

response = requests.post(upload_url, files=file)
json_data = json.loads(response.text)
json_data

{'file': '2000000001|0|-1|909528|3782ff96f9|csv|2745|top_ctr_data.csv|fe643031044520b44d03e52d7c963f12|c6324f5757565f6a74d4333730abae6f||||eyJkaXNrIjoiMTMiLCJzdDJfc2hhIjoiNzZkNjQ1NTk2NDFlNDVlNWMxMmQ5Yzg5MGY4MDU4OTVhMzEyMjc1OTc0OWEyM2JhMTZiN2RmN2IiLCJzdDJfc2VjcmV0IjotOTE3NTQxMTgwOTgwOTA0MzI0NSwicGVlcl9zZW5kZXIiOiItMjM3MDYzNzcxIn0='}