In [101]:
import pandas as pd
from datetime import datetime

In [102]:
df = pd.read_csv('D:\\Программы\\Karpov.Courses - Аналитик данных (2022)\\Часть 1\\Задания\\Ноутбуки и датасеты\\Ноутбуки и датасеты\\lesson_1_data.csv' , sep = ';')

In [103]:
df = df.rename(columns = {'Номер': 'number',
                'Дата создания': 'create_date',
                'Дата оплаты': 'payment_day' ,
                'Title': 'title' ,
                'Статус': 'status' ,
                'Заработано': 'money' ,
                'Город': 'city' ,
                'Платежная система': 'payment_system'})

In [129]:
df.head()

,number,create_date,payment_day,title,status,money,city,payment_system
0,1062823,01.12.2019 10:50,01.12.2019 10:52,Курс обучения «Эксперт»,Завершен,29597.5,Чита,Сбербанк эквайринг
1,1062855,01.12.2019 20:53,01.12.2019 21:27,Курс обучения «Эксперт»,Завершен,17450.3,Краснодар,Яндекс.Касса
2,1062856,01.12.2019 21:43,NaN,Курс обучения «Специалист»,Отменен,0.0,NaN,NaN
3,1062880,03.12.2019 0:18,NaN,Курс обучения «Консультант»,Отменен,0.0,г.Москва и Московская область,NaN
4,1062899,03.12.2019 21:43,NaN,Курс обучения «Эксперт»,Отменен,0.0,г.Москва и Московская область,NaN

In [130]:
df[['title', 'status']]

                                                 title    status
0                              Курс обучения «Эксперт»  Завершен
1                              Курс обучения «Эксперт»  Завершен
2                           Курс обучения «Специалист»   Отменен
3                          Курс обучения «Консультант»   Отменен
4                              Курс обучения «Эксперт»   Отменен
..                                                 ...       ...
287  Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...  Завершен
288                        Курс обучения «Консультант»   Отменен
289                        Курс обучения «Консультант»  Завершен
290  Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...  Завершен
291  Курс от Школы Диетологов. Повышение квалификац...  Завершен

[292 rows x 2 columns]

In [142]:
df.money.sum()

np.float64(992103.5900000001)

In [132]:
all_money = df.money.sum()

In [133]:
money_by_city = df \
    .groupby(['title', 'city'], as_index = False) \
    .aggregate({'money': 'sum'}) \
    .sort_values('money', ascending = False)

In [134]:
money_by_city.money.sum()

np.float64(969329.8700000001)

In [135]:
money_by_city.to_csv('money_by_city.to_csv', index=False)

In [136]:
money_gr = df \
    .query("status == 'Завершен'") \
    .groupby(['title', 'city'], as_index = False) \
    .aggregate({'money': 'sum', 'number' : 'count'}) \
    .sort_values('money', ascending = False) \
    .rename(columns={'number': 'succes_order'})

In [137]:
today_day = datetime.today().strftime('%Y-%m-%d')
file_name = 'money_title_{}.csv'
file_name.format(today_day)

'money_title_2025-12-22.csv'

In [143]:
money_gr

,title,city,money,succes_order
32,Курс обучения «Эксперт»,г.Санкт-Петербург и Ленинградская область,59195.00,2
107,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,г.Москва и Московская область,46967.04,16
29,Курс обучения «Эксперт»,Балхаш,42750.00,1
58,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Краснодарский край,38169.78,13
25,Курс обучения «Специалист»,"Московская область, г. Подольск",29695.70,1
...,...,...,...,...
45,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Алматы,2914.30,1
9,Курс обучения «Консультант»,Москва,2.00,2
15,Курс обучения «Консультант»,София,1.00,1
8,Курс обучения «Консультант»,Люберцы,1.00,1
21,Курс обучения «Консультант»,москва,1.00,1

In [139]:
money_gr.money.sum()

np.float64(969329.8700000002)

In [140]:
all_money

np.float64(992103.5900000001)

In [141]:
today_day = datetime.today().strftime('%Y-%m-%d')

In [117]:
file_name = 'money_title_{}.csv'

In [118]:
file_name.format(today_day)

'money_title_2025-12-22.csv'