In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('D:\\Программы\\Karpov.Courses - Аналитик данных (2022)\\Часть 1\\Задания\\Данные для Минипроектов\\5_transaction_data_updated.csv')

In [16]:
df.head()

                 name  minute  transaction
0  Ekaterina_Fedorova       0            1
1  Ekaterina_Fedorova       1            1
2  Ekaterina_Fedorova       2            1
3  Ekaterina_Fedorova       3            1
4  Ekaterina_Fedorova       4            1

In [14]:
df1 = df.groupby(['name', 'minute'], as_index = False).agg({'transaction' : 'count'})
user_vs_minute_pivot = pd.pivot_table(df1, columns = 'name', index = 'minute', values = 'transaction').fillna(0)

In [17]:
df['true_minute'] =

                    name  minute  transaction
0     Ekaterina_Fedorova       0            1
1     Ekaterina_Fedorova       1            1
2     Ekaterina_Fedorova       2            1
3     Ekaterina_Fedorova       3            1
4     Ekaterina_Fedorova       4            1
...                  ...     ...          ...
2573   Vasilisa_Smirnova      52            1
2574   Vasilisa_Smirnova      53            1
2575   Vasilisa_Smirnova      54            1
2576   Vasilisa_Smirnova      56            1
2577   Vasilisa_Smirnova      58            1

[2578 rows x 3 columns]